name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: MRK4863/Traffic-Sign-Classifier-with-GUI.git
        huggingface_repo_id: MRK4863/traffic
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}
